import random
a = random.randint(1,7)
print('randint:', a)
b= random.uniform(1,4)
print('uniform:', b)
c=random.random()
print('random:', c)
d= random.randrange(1,10,2)
print('randrange:', d)
e=random.getstate()
print('getstate:', e)
f=random.betavariate(alpha=2.3, beta=3.76)
print('betavariate:', f)
g= random.choice(['Good', 'better', 'Best'])
print('choice:', g)
h= random.choices(['mango', 'banana', 'orange', 'peach'],[3,2,0.5,1], k=6)
print('choices function:', h)
i= random.expovariate(1/6)
print('expovariate:', i)
name_list = 'sanji shifa nahid jarif'.split()
random.shuffle(name_list)
print('shuffled list:', name_list)
